networks:
  shared-network:
    driver: bridge

services:
  kafka-ui:
    container_name: kafka-ui 
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka-1
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9094
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - shared-network
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  kafka-1:
    image: 'bitnami/kafka:3.8.0'
    networks:
      - shared-network
    ports:
      - 29091:9094
    expose:
      - "9092"
      - "9093"
      - "9094"
      - "9101"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093
      KAFKA_CFG_TRANSACTION_PARTITION_VERIFICATION_ENABLE: false
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,EXTERNAL://kafka-1:9094
      KAFKA_ENABLE_KRAFT: yes
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: XkpGZQ27R3eTl3OdTm2LYA # 16 byte base64-encoded UUID

